/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-10-12 09:31:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Ass8Q3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("	<head><title> Entity Relationship </title></head>\n");
      out.write("	<style>\n");
      out.write("		h1{color : darkorange; text-align: center;}\n");
      out.write("		table\n");
      out.write("		{\n");
      out.write("			background-color:lightblue;\n");
      out.write("		}\n");
      out.write("	</style>\n");
      out.write("	<body>\n");
      out.write("		");

			Connection cn = null;
			Statement st = null;
			ResultSet rs = null;
			String qry = null;
			int r = Integer.parseInt(request.getParameter("a1"));
			int i = 0;
			try
			{
				Class.forName("com.mysql.cj.jdbc.Driver");
				cn=DriverManager.getConnection("jdbc:mysql://192.168.28.3:3306/syca221574","syca221574","");
		
			if(r == 1)
			{
				qry = "select * from Employe";
				
				st = cn.createStatement();
				rs = st.executeQuery(qry);
		
      out.write("\n");
      out.write("			<center>\n");
      out.write("			<h1>Database Details</h1><br>\n");
      out.write("			<h3>Employee Table</h3>\n");
      out.write("			<table border=1>\n");
      out.write("				<tr>\n");
      out.write("					<th>SR No.</th>\n");
      out.write("					<th>Emp ID</th>\n");
      out.write("					<th>Emp Name</th>\n");
      out.write("					<th>Emp Salary</th>\n");
      out.write("					<th>Dept No</th>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i = 1;
			while(rs.next())
			{
				
		
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<td>");
 out.println(i); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("eno")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getString("ename")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("sal")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("dno")); 
      out.write("</td>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i++;
			}
		
      out.write("\n");
      out.write("			</table>\n");
      out.write("			</center>\n");
      out.write("			<br>\n");
      out.write("		");

			qry = "select * from Department";
			st = cn.createStatement();
			rs = st.executeQuery(qry);
		
      out.write("\n");
      out.write("			<center>\n");
      out.write("			<h3>Department Table</h3>\n");
      out.write("			<table border=1>\n");
      out.write("				<tr>\n");
      out.write("					<th>SR No.</th>\n");
      out.write("					<th>Dept No</th>\n");
      out.write("					<th>Dept Name</th>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i = 1;
			while(rs.next())
			{
				
		
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<td>");
 out.println(i); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("dno")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getString("dname")); 
      out.write("</td>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i++;
			}
		
      out.write("\n");
      out.write("			</table>\n");
      out.write("			</center>\n");
      out.write("			<br>\n");
      out.write("		");

			qry = "select * from Project";
			st = cn.createStatement();
			rs = st.executeQuery(qry);
		
      out.write("\n");
      out.write("			<center>\n");
      out.write("			<h3>Project Table</h3>\n");
      out.write("			<table border=1>\n");
      out.write("				<tr>\n");
      out.write("					<th>SR No.</th>\n");
      out.write("					<th>Project Name</th>\n");
      out.write("					<th>No of days</th>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i = 1;
			while(rs.next())
			{
				
		
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<td>");
 out.println(i); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getString("pname")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("no_of_days")); 
      out.write("</td>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i++;
			}
		
      out.write("\n");
      out.write("			</table>\n");
      out.write("			</center>\n");
      out.write("			<br>\n");
      out.write("		");

			qry = "select * from emp_pro";
			st = cn.createStatement();
			rs = st.executeQuery(qry);
		
      out.write("\n");
      out.write("			<center>\n");
      out.write("			<h3>Emp_Project Table</h3>\n");
      out.write("			<table border=1>\n");
      out.write("				<tr>\n");
      out.write("					<th>SR No.</th>\n");
      out.write("					<th>Project name</th>\n");
      out.write("					<th>Employee ID</th>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i = 1;
			while(rs.next())
			{
				
		
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<td>");
 out.println(i); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getString("pname")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("eno")); 
      out.write("</td>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i++;
			}
		
      out.write("\n");
      out.write("			</table>\n");
      out.write("			</center>\n");
      out.write("			<center>\n");
      out.write("			<br><br><button><a href=Ass8Q3.html>Go Back</a></button>\n");
      out.write("		");

			}
			else if(r == 2)
			{
				qry = "select e.* from Employe e,Project p,emp_pro ep where e.eno = ep.eno and p.pname = ep.pname and ep.pname = 'Inventory control project'";
				st = cn.createStatement();
				rs = st.executeQuery(qry);
		
      out.write("\n");
      out.write("			<br>\n");
      out.write("			</center>\n");
      out.write("			<center>			\n");
      out.write("			<h3>1. Details of all employees working on Inventory control project</h3></br>\n");
      out.write("			<table border=1>\n");
      out.write("				<tr>\n");
      out.write("					<th>SR No.</th>\n");
      out.write("					<th>Emp ID</th>\n");
      out.write("					<th>Emp Name</th>\n");
      out.write("					<th>Emp Salary</th>\n");
      out.write("					<th>Dept No</th>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i = 1;
			while(rs.next())
			{
				
		
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<td>");
 out.println(i); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("eno")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getString("ename")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("sal")); 
      out.write("</td>\n");
      out.write("					<td>");
 out.println(rs.getInt("dno")); 
      out.write("</td>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("		");

			i++;
			}
		
      out.write("\n");
      out.write("			</table>\n");
      out.write("			</center>\n");
      out.write("			<center>\n");
      out.write("			<br><button><a href=Ass8Q3.html>Go Back</a></button>\n");
      out.write("\n");
      out.write("		");

			}
			else
			{
					qry = "select * from Employe where dno in(select dno from Department where dname = 'CA')";
					st = cn.createStatement();
					rs = st.executeQuery(qry);

		
      out.write("\n");
      out.write("				<br>\n");
      out.write("			</center>\n");
      out.write("			<center>\n");
      out.write("				<h3>2. Details of all employees of Computer Department</h3></br>\n");
      out.write("				<table border=1>\n");
      out.write("					<tr>\n");
      out.write("						<th>SR No.</th>\n");
      out.write("						<th>Emp ID</th>\n");
      out.write("						<th>Emp Name</th>\n");
      out.write("						<th>Emp Salary</th>\n");
      out.write("					</tr>\n");
      out.write("					\n");
      out.write("		");

				i = 1;
				while(rs.next())
				{
					
		
      out.write("\n");
      out.write("					<tr>\n");
      out.write("						<td>");
 out.println(i); 
      out.write("</td>\n");
      out.write("						<td>");
 out.println(rs.getInt("eno")); 
      out.write("</td>\n");
      out.write("						<td>");
 out.println(rs.getString("ename")); 
      out.write("</td>\n");
      out.write("						<td>");
 out.println(rs.getInt("sal")); 
      out.write("</td>\n");
      out.write("					</tr>\n");
      out.write("					\n");
      out.write("		");

				i++;
				}
		
      out.write("\n");
      out.write("				</table>\n");
      out.write("				</center>\n");
      out.write("				<center>\n");
      out.write("				<br><button><a href=Ass8Q3.html>Go Back</a></button>\n");
      out.write("				</center>\n");
      out.write("		");

			}						
			}
			catch(Exception e)
			{
				System.out.println(e);
			}
			finally
			{
				try
				{
					cn.close();
				}
				catch(SQLException se)
				{
					System.out.println(se);
				}
			}
		
      out.write("\n");
      out.write("	</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
