/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-11-09 09:10:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"A10Error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<title>Register</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");

	Connection cn = null;
	PreparedStatement ps = null;
	Statement stmt = null;
	ResultSet rs = null;
	Statement stmt1 = null;
	ResultSet rs1 = null;
	String rn = request.getParameter("rollNo");
	String nm = request.getParameter("name");
	String co = request.getParameter("course");
	String ev = request.getParameter("event");
	
	try
	{
		Class.forName("com.mysql.cj.jdbc.Driver");
		cn = DriverManager.getConnection("jdbc:mysql://192.168.28.3:3306/syca221574","syca221574","");
		
		stmt = cn.createStatement();
		rs = stmt.executeQuery("select * from student_event where roll_no='"+rn+"' and event_name='"+ev+"'");
		stmt1 = cn.createStatement();
		rs1 = stmt1.executeQuery("select * from student where roll_no='"+rn+"' and course_name='"+co+"'");
		
		if(rs.next() && !rs1.next())
			throw new Exception("Student with this roll no already exist, please check course details");
			
		stmt = cn.createStatement();
		rs = stmt.executeQuery("select * from student_event where roll_no='"+rn+"' and event_name='"+ev+"'");
		stmt1 = cn.createStatement();
		rs1 = stmt1.executeQuery("select * from student where roll_no='"+rn+"' and course_name='"+co+"'");
		
		if(rs.next())
			throw new Exception("Student with this roll no already registered for this event");
			
		stmt = cn.createStatement();
		rs = stmt.executeQuery("select * from student_event where roll_no='"+rn+"' and event_name='"+ev+"'");
		stmt1 = cn.createStatement();
		rs1 = stmt1.executeQuery("select * from student where roll_no='"+rn+"' and course_name='"+co+"'");
		
		if(rs1.next())
		{
			ps = cn.prepareStatement("insert into student_event values(?,?)");
			ps.setString(1,rn);
			ps.setString(2,ev);
			ps.executeUpdate();
			out.println("<h1>Registration Successful</h1><br>");
			out.println("<a href='A10Q1.html'>Main Page</a>");
		}
		
		stmt = cn.createStatement();
		rs = stmt.executeQuery("select * from student_event where roll_no='"+rn+"' and event_name='"+ev+"'");
		stmt1 = cn.createStatement();
		rs1 = stmt1.executeQuery("select * from student where roll_no='"+rn+"' and course_name='"+co+"'");
		
		if(!rs.next() && !rs1.next())
		{ 
			stmt = cn.createStatement();
			rs = stmt.executeQuery("select * from student where roll_no='"+rn+"'");
			if(rs.next())
				throw new Exception("Student with this roll no already exist, please check course details");
			else
			{
				ps = cn.prepareStatement("insert into student values(?,?,?)");
				ps.setString(1,rn);
				ps.setString(2,nm);
				ps.setString(3,co);
				ps.executeUpdate();
				
				ps = cn.prepareStatement("insert into student_event values(?,?)");
				ps.setString(1,rn);
				ps.setString(2,ev);
				ps.executeUpdate();
				out.println("<h1>Registration Successful</h1>");
				out.println("<a href='A10Q1.html'>Main Page</a>");
			}
		}
	}
	catch(SQLException e)
	{
		throw new Exception(e);
	}
	catch(ClassNotFoundException ce)
	{
		throw new Exception(ce);
	}
	finally
	{
		try
		{
			cn.close();
		}
		catch(SQLException e)
		{
			throw new Exception(e);
		}
	}

      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>			\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
